# -*- coding: utf-8 -*-
"""Live Coding Session - API Integration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xcP5HsenwzTsGXxJ2d8fFmTvtoJA9xXf
"""

!pip install requests

api_url = "https://api.openweathermap.org/data/2.5/weather"
 api_key = "3585d0bfaf3cb9197c6d92b947adc589"
 params = {
        'q': city,
        'appid': api_key,
        'units': 'metric'  # For temperature in Celsius
    }
response = requests.get(api_url, params=params)
data = response.json()
print(data)

import requests

def get_weather_data(city):
    # Base URL for OpenWeatherMap API
    api_url = "https://api.openweathermap.org/data/2.5/weather"
    api_key = "3585d0bfaf3cb9197c6d92b947adc589"

    # Parameters for the API request
    params = {
        'q': city,
        'appid': api_key,
        'units': 'metric'  # For temperature in Celsius
    }

    try:
        # Make an API request
        response = requests.get(api_url, params=params)

        # Handle the response
        if response.status_code == 200:
            # Parse JSON data
            data = response.json()
            display_weather_data(data)
        elif response.status_code == 404:
            print(f"Error: City '{city}' not found.")
        else:
            print(f"Error: Unable to fetch data. Status code: {response.status_code}")

    except requests.exceptions.RequestException as e:
        print(f"Error: Unable to connect to the API. {e}")

def display_weather_data(data):
    # Extract relevant information from the data
    city_name = data.get('name')
    weather = data.get('weather', [{}])[0].get('description', 'No description')
    temperature = data.get('main', {}).get('temp', 'No data')
    humidity = data.get('main', {}).get('humidity', 'No data')

    # Display the data in a user-friendly format
    print(f"Weather in {city_name}:")
    print(f"  Description: {weather}")
    print(f"  Temperature: {temperature}°C")
    print(f"  Humidity: {humidity}%")

if __name__ == "__main__":
    # Get city input from the user
    city = input("Enter the city name: ")
    get_weather_data(city)

